framework:
  secret: '%env(APP_SECRET)%'
  router:
    utf8: true
  trusted_proxies: '%env(TRUSTED_PROXIES)%'
  trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix']
  handle_all_throwables: true
  http_method_override: false
  php_errors:
    log: true
  lock: 'flock'
  cache:
    pools:
      cache.journey_search_rate_limiter:
        adapter: cache.adapter.filesystem
  rate_limiter:
    journey_search:
      policy: fixed_window
      limit: 20
      interval: '1 minute'
      cache_pool: cache.journey_search_rate_limiter
      lock_factory: lock.factory
  asset_mapper:
    paths: ['%kernel.project_dir%/assets/']
when@test:
  framework:
    test: true
