services:
  _defaults:
    autowire: true
    autoconfigure: true
  App\:
    resource: '../src/'
    exclude: '../src/{Kernel.php,Trip,Environmental,Accommodation,Provider}/'
  App\Provider\DemoAccommodationProvider: ~
  App\Provider\AccommodationProvider: '@App\Provider\DemoAccommodationProvider'
